### ISSUE TITLE
AppImage integration does not work properly

### ISSUE THREAD

**Issue by lehtoroni** [lehtoroni/lmath-issues#24]
Some Linux distributions ask if the user wants to integrate the AppImage to their system, but if the user chooses to do so, nothing happens.

> Käynnistysikonia se ei näytä luovan ja se täytyy käynnistää terminaalista ./LMath..

**Comment by probonopd** [comment]
> Some Linux distributions ask if the user wants to integrate the AppImage to their system

That behavior is no longer recommended. We recommend to use [appimaged](https://github.com/AppImage/appimaged) or tools like AppImageLauncher instead if you want desktop integration.

**Comment by lehtoroni** [comment]
**Fix in r1.7:**

> #24; Electronin ja käytettyjen aputyökalujen versiot on päivitetty
(Updated versions of Electron and build tools)
