### ISSUE TITLE
Ctrl + Z for formula editor

### ISSUE THREAD

**Issue by TatuLaras** [lehtoroni/lmath-issues#30]
Would be nice to have an undo functionality for the formula editor.

**Comment by lehtoroni** [comment]
> Would be nice to have an undo functionality for the formula editor.

https://github.com/digabi/rich-text-editor/issues
Please contact YTL/SEN for any requests/additions/issues regarding the rich text editor itself.

**Comment by lehtoroni** [comment]
Further development will be tracked on https://github.com/lehtoroni/lmath-issues/issues/41
