### ISSUE TITLE
A high resolution image in a document causes write EOF error when exporting as a PDF

### ISSUE THREAD

**Issue by 17ms** [lehtoroni/lmath-issues#46]
### Description

Adding a relatively high resolution image to a document and trying to export the document as a PDF often causes an error:
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: write EOF
  at WriteWrap.onWriteComplete [as oncomplete]
(node:internal/stream_base_commons:94:16)
```

After which L'Math throws a generation timeout error:
```
Error: 
Error: Generation timeout
```

### Steps to Reproduce

1. Create an empty document
2. Add an image (e.g. JPEG, PNG) to the document
3. Export the document as a PDF

### Context

```
OS version: Windows 11 Pro 22H2, build 22621.1265

Platform: win32
Architecture: ia32

Node version: v16.15.0
v8 version: 10.4.132.24-electron.0
Electron version: 20.2.0

Software base version: r1.9
Software patch: r1.9_23
```

**Comment by lehtoroni** [comment]
Should be fixed in full release r1.10.0. The new release now uses Electron's built-in pdf export method instead of Phantomjs, and saves all data into a temporary HTML file.
