### ISSUE TITLE
[Beta r1.10] Creating new worksheet keeps old filename

### ISSUE THREAD

**Issue by juusolain** [lehtoroni/lmath-issues#56]
Creating a new worksheet from file -> new worksheet doesn't reset filename. This leads to a situation where you can accidentally overwrite the worksheet open before by saving the new empty worksheet over the old one, instead of it asking for a new filename. This is especially easy when using ctrl + S to save a worksheet.

**Comment by lehtoroni** [comment]
@juusolain Could you please tell the used L'Math version (and patch number if on r1.9), and give exact steps for reproducing the issue? I wasn't able to repeat this on the latest non-beta version (r1.9_26), so, is does this only happen on an earlier version, or a pre-release?

**Comment by juusolain** [comment]
This happens only on the pre-release r1.10. Tested with win10, unsure about other platforms.
Reproduction steps:
1. Open a saved file (or create & save a new file)
2. File -> New Document
3. Observe that the document filename doesn't change in the window title
4. Save the new document (ctrl + S or via file -> save)
5. The old document is now overwritten even though the app should ask for a filename when saving a new file.

**Comment by lehtoroni** [comment]
Fixed in full release r1.10.0.
