### ISSUE TITLE
No such file or directory error when launching linux version installed with script

### ISSUE THREAD

**Issue by SampoVirtanen** [lehtoroni/lmath-issues#76]
**Please read and check...** (change `[ ]` to `[x]`)
- [x] I have installed the latest stable version of the software (ignore if using a beta version)
- [x] The issue or behavior does not reproduce on the [Digabi "Math Demo"](https://math-demo.abitti.fi/)

**Describe the issue**
When I install the software using the script `wget -qO - "https://lehtodigital.fi/f/2Lu5T" | bash <(cat) </dev/tty` from [https://lehtodigital.fi/lmath/download](https://lehtodigital.fi/lmath/download), and then try to start it(KDE start menu, ~/.lmath/LMath.AppImage or ~/.lmath/lmath.desktop), it doesn't start. When I try to launch it from the terminal with `~/.lmath/LMath.AppImage` it fails with `line 1: url:https://api.github.com/repos/lehtoroni/lmath-issues/releases/171833780: No such file or directory`. If I download the .AppImage from [https://lehtodigital.fi/lmath/download](https://lehtodigital.fi/lmath/download) and replace the .AppImage in ~/.lmath with it, the app launches. It seems like there's something wrong with the installation script, or the version of the software it downloads.

**General information**
- Fedora 40 KDE

**Comment by lehtoroni** [comment]
Seems that Github's REST API will sometimes return non-pretty-printed JSON, which seems to cause the installation script to freak out due to the rest of the JSON being included.

Will work on an improved installation script, which does not rely on Github's JSON being pretty printed...

**Comment by lehtoroni** [comment]
Here is an updated installation script:

```bash
wget -qO - "https://lehtodigital.fi/f/IIlmS" | bash <(cat) </dev/tty
```

Would @SampoVirtanen have the time to try it out?

**Comment by SampoVirtanen** [comment]
Just tried it out. Works perfectly now. Thanks.

**Comment by lehtoroni** [comment]
Great! The new install script can now be found on the website as well!
