### ISSUE TITLE
On the Linux AppImage, when the app loses focus and regains it, you have to click the text field before you can type again

### ISSUE THREAD

**Issue by Jorma17** [lehtoroni/lmath-issues#79]
**Please read and check...** (change `[ ]` to `[x]`)
- [x] I have installed the latest stable version of the software (ignore if using a beta version)
- [x] The issue or behavior does not reproduce on the [Digabi "Math Demo"](https://math-demo.abitti.fi/)

**Describe the issue**

If you install the AppImage for Linux, make a new L'Math document and start typing, and then make the application window lose focus (for example, by alt-tabbing to another app) and going back to the app, the typing cursor disappears and you have to click on the text field again before being able to type anything.

**Screenshots**

**General information**
- **Program version:** r1.10.7
- **Operating system:** Arch Linux with KDE Plasma Wayland and kernel version 6.10.8

**Comment by lehtoroni** [comment]
Was able to reproduce this, and will work on a fix soon!

**Comment by lehtoroni** [comment]
This will be fixed in 1.10.9:
- [227031980f](https://git.lehtodigital.fi/lehtoroni/LMath/commit/227031980f7c9ae7bdca73b64144e5df01493268) Focus to top webContents when focusing to window (fix [#79](https://git.lehtodigital.fi/lehtoroni/LMath/issues/79))

**Comment by lehtoroni** [comment]
Fixed in 1.10.9.
